---
- name: FinGuard Setup
  hosts: FinGuard
  become: yes

  roles:
    - FinGuard

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Restart Discovery Proxy
      systemd:
        name: jellyfin-discovery-proxy
        state: restarted