# --------------------------------------------------
# Package Installation
# --------------------------------------------------

# Ensures the APT package cache is updated before installing new packages.
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
  tags: [packages]

# Installs a list of essential packages required for the system's functionality.
- name: Install required packages
  apt:
    name:
      - wireguard-tools
      - nginx
      - avahi-daemon
      - resolvconf
      - cron
      - openssl
      - jq
      - bc
    state: present
  tags: [packages]

# --------------------------------------------------
# System Configuration
# --------------------------------------------------

# Sets the system's timezone based on the 'timezone' variable.
- name: Set system timezone
  timezone:
    name: "{{ timezone }}"

# --------------------------------------------------
# Hostname Setup
# --------------------------------------------------

# Sets the system's static and transient hostname in a reliable and persistent way.
- name: Set system hostname
  hostname:
    name: "{{ hostname }}"
  tags: [hostname]

# Updates the /etc/hosts file to ensure the new hostname resolves correctly to the loopback address.
- name: Update /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1.*'
    line: "127.0.1.1       {{ hostname }}.local {{ hostname }}"
    owner: root
    group: root
    mode: '0644'
  tags: [hostname]

# --------------------------------------------------
# User Management & Updates
# --------------------------------------------------

# Optionally resets the 'pi' user's password if 'pi_password' is defined and not empty.
- name: Optionally reset pi password
  shell: echo "pi:{{ pi_password }}" | chpasswd
  when: pi_password is defined and pi_password != ""
  no_log: true

# Updates the APT package cache and upgrades all installed packages.
- name: Update apt cache and upgrade all packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: [packages, updates]